"use client";

import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, CalendarDays, CircleHelp, ImageIcon, Monitor, Settings, Upload, Warehouse } from "lucide-react";
import { useState } from "react";

export default function PromotionResolutionPage() {
  const [fileName, setFileName] = useState("");
  const [submitted, setSubmitted] = useState(false);

  return <main className="min-h-screen bg-[#f3f3f3] px-4 pb-12 pt-20 text-[#1a1c1c] sm:px-6 lg:px-8 lg:pt-8"><div className="mx-auto max-w-[1380px]">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-[28px] font-bold sm:text-[32px]">Summer Fleet Showcase</h1><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-medium text-red-500">ⓘ Issue Detected</span></div><p className="mt-1 text-base text-[#5f5e5e]">Promotions &amp; Ads / Resolution Center</p></div><div className="flex gap-3"><Link href="/admin/advertisements/promotions" className="grid h-11 place-items-center rounded-lg border border-[#926f6b] bg-white px-6 text-sm">Discard Changes</Link><button onClick={() => setSubmitted(true)} className="h-11 rounded-lg bg-[#fe1118] px-7 text-sm font-semibold text-white">Save &amp; Re-submit</button></div></header>
    {submitted && <p className="mt-4 rounded-lg bg-green-50 p-3 text-sm font-medium text-green-700">Campaign has been re-submitted for quality review.</p>}

    <section className="mt-10 flex gap-5 rounded-xl border border-[#fe1118] bg-red-50 p-6"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-[#fe1118] text-white"><AlertTriangle className="size-6" /></span><div><h2 className="text-xl font-semibold text-[#fe1118]">Action Required: Low Resolution Image</h2><p className="mt-2 max-w-5xl text-sm leading-6 text-[#5c403d]">The current creative for “Summer Fleet Showcase” fails quality assurance. Image quality is too low for high-resolution displays (Retina/4K). Please upload a new asset with a width of 1200px or greater to ensure brand consistency across all customer devices.</p></div></section>

    <div className="mt-10 grid gap-8 xl:grid-cols-[1fr_320px]"><div className="space-y-8"><section className="rounded-xl border border-red-200 bg-white p-7 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-[#5f5e5e]">Current Asset</p><div className="relative mt-6 h-[400px] overflow-hidden rounded-lg"><Image src="/img/admin/promo-resolution-car.png" alt="Current Summer Fleet Showcase banner" fill className="object-cover" /><div className="absolute inset-0 grid place-items-center"><span className="flex items-center gap-3 rounded-xl bg-white px-7 py-4 text-lg font-semibold shadow-lg"><AlertTriangle className="size-5 text-red-500" />Needs Replacement</span></div></div><div className="mt-5 flex flex-col gap-2 text-sm text-[#5f5e5e] sm:flex-row sm:justify-between"><span>summer_fleet_v1_legacy.jpg</span><span>800 x 450 px (Too Small)</span></div></section>
      <label className="block cursor-pointer rounded-xl border border-dashed border-red-300 bg-white p-10 text-center"><input type="file" accept="image/*" className="sr-only" onChange={event => setFileName(event.target.files?.[0]?.name || "")} /><span className="mx-auto grid size-14 place-items-center rounded-full bg-neutral-100 text-red-500"><Upload className="size-6" /></span><h2 className="mt-5 text-xl font-semibold">{fileName || "Upload High-Res Banner"}</h2><p className="mx-auto mt-2 max-w-lg text-sm text-[#5f5e5e]">Drag and drop your file here, or click to browse files from your computer.</p><div className="mx-auto mt-10 grid max-w-2xl gap-5 sm:grid-cols-3">{[[ImageIcon,"Width","Min 1200px"],[Monitor,"Ratio","16:9"],[Warehouse,"Max Size","5 MB"]].map(([Icon,label,value]) => {const TileIcon = Icon as typeof ImageIcon; return <span key={label as string} className="flex items-center gap-3 rounded-lg border border-red-200 bg-[#f3f3f3] p-5 text-left"><TileIcon className="size-5 text-red-500" /><span><small className="block text-xs">{label as string}</small><strong>{value as string}</strong></span></span>})}</div></label></div>

      <aside className="space-y-6"><section className="rounded-xl border border-red-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-[#5f5e5e]">Campaign Context</p><div className="mt-7 space-y-6">{[[Monitor,"Placement","Homepage Hero Banner"],[CalendarDays,"Visibility Window","Jun 01 – Aug 31, 2024"]].map(([Icon,label,value]) => {const RowIcon = Icon as typeof Monitor; return <div key={label as string}><p className="mb-2 text-xs text-[#5f5e5e]">{label as string}</p><div className="flex items-center gap-3 rounded-lg bg-[#f3f3f3] p-4"><RowIcon className="size-5" /><strong>{value as string}</strong></div></div>})}<div><p className="mb-2 text-xs text-[#5f5e5e]">Vendor</p><div className="flex items-center gap-3 rounded-lg bg-[#f3f3f3] p-4"><span className="grid size-9 place-items-center rounded-full bg-red-500 text-[10px] font-bold text-white">CPG</span><div className="flex-1"><strong className="block">Cambodia Pro Gear</strong><span className="text-sm text-[#5f5e5e]">VND-1024</span></div><Settings className="size-5" /></div></div></div><hr className="my-6 border-red-200" /><p className="text-xs text-[#5f5e5e]">Technical History</p><div className="mt-4 space-y-5"><div className="flex gap-3"><span className="mt-2 size-2 rounded-full bg-red-500" /><div><strong>Flagged by QA System</strong><p className="text-xs text-[#5f5e5e]">Today, 09:42 AM • System Bot</p></div></div><div className="flex gap-3 opacity-50"><span className="mt-2 size-2 rounded-full bg-neutral-500" /><div><strong>Campaign Created</strong><p className="text-xs text-[#5f5e5e]">Yesterday, 04:15 PM • Admin</p></div></div></div></section><section className="rounded-xl border border-red-200 bg-[#eee] p-6"><h3 className="flex items-center gap-3 text-lg"><CircleHelp className="size-5 text-red-500" />Need Help?</h3><p className="mt-2 text-sm leading-6 text-[#5f5e5e]">Contact the design team if you can&apos;t access high-res assets.</p><button className="mt-6 h-12 w-full rounded-lg border border-[#926f6b] bg-white text-red-500">Contact Support</button></section></aside></div>
  </div></main>;
}
