import Image from "next/image";
import { AlertTriangle, ArrowRight, Check, ChevronLeft, ChevronRight, Clock3, CreditCard, FileCheck2, History, Pencil, ShieldCheck, Star, TrendingUp, UserRound } from "lucide-react";

const bookings = [
  ["BK-89231", "Lakeside Manor Villa", "Lake Tahoe, CA", "May 12 – May 16, 2025", "4 nights", "Completed", "$1,450.00", "/img/admin/property-lakeside.png"],
  ["BK-88217", "Industrial Loft Office", "San Francisco, CA", "Apr 28 – Apr 30, 2025", "2 nights", "Active", "$320.00", "/img/admin/property-office.png"],
  ["BK-87104", "Executive Suite 4B", "Los Angeles, CA", "May 20 – May 23, 2025", "3 nights", "Scheduled", "$890.00", "/img/admin/property-suite.png"],
  ["BK-87107", "Executive Suite 4B", "Los Angeles, CA", "May 20 – May 23, 2025", "3 nights", "Scheduled", "$890.00", "/img/admin/property-suite.png"],
  ["BK-87109", "Executive Suite 4B", "Los Angeles, CA", "May 20 – May 23, 2025", "3 nights", "Scheduled", "$890.00", "/img/admin/property-suite.png"],
];

const activity = [
  { title: "Account created", detail: "User registered and account was created successfully.", date: "Oct 12, 2023", time: "10:24 AM", actor: "System", icon: UserRound, color: "bg-red-50 text-red-400" },
  { title: "Identity verification submitted", detail: "User submitted ID documents for verification.", date: "May 08, 2025", time: "02:15 PM", actor: "System", icon: AlertTriangle, color: "bg-orange-50 text-orange-400" },
  { title: "Identity verification under review", detail: "Documents are under admin review.", date: "May 13, 2025", time: "11:42 AM", actor: "Admin User", icon: FileCheck2, color: "bg-red-50 text-red-500", current: true },
  { title: "Admin note added", detail: "Requested additional document for address verification.", date: "May 13, 2025", time: "11:45 AM", actor: "Admin User", icon: History, color: "bg-neutral-100 text-neutral-500" },
];

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <section className={`rounded-2xl border border-[#e3e7eb] bg-white shadow-[0_1px_2px_rgba(0,0,0,0.04)] ${className}`}>{children}</section>;
}

export default function AdminUserDetailPage() {
  return (
    <main className="min-h-screen bg-[#f3f3f3] px-4 pb-10 pt-20 sm:px-6 lg:px-8 lg:pt-8">
      <div className="mx-auto max-w-[1380px] space-y-6">
        <header className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-4"><Image src="/img/admin/detail-avatar.png" alt="Hean Sitha" width={64} height={64} className="size-16 rounded-xl object-cover" priority /><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-[#151c23]">Hean Sitha</h1><span className="rounded-full bg-green-50 px-2 py-1 text-[9px] font-bold uppercase text-green-600">Verified</span></div><p className="mt-1 text-xs text-[#77797b]">User ID: #USR-9283-AT &nbsp; · &nbsp; Joined: Oct 12, 2023</p></div></div>
          <div className="flex flex-wrap gap-3"><button className="h-10 rounded-xl border bg-white px-5 text-xs font-bold">Warn User</button><button className="h-10 rounded-xl border border-red-200 bg-red-50 px-5 text-xs font-bold text-red-600">Suspend Account</button><button className="h-10 rounded-xl bg-[#f73030] px-5 text-xs font-bold text-white">Quick Actions</button></div>
        </header>

        <div className="grid gap-6 xl:grid-cols-[2fr_1fr]">
          <Card className="p-6"><div className="flex justify-between"><h2 className="font-bold">Personal Profile</h2><button className="flex items-center gap-1 text-xs font-bold text-red-600"><Pencil className="size-3" /> Edit Details</button></div><dl className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{[["Full Name","Alex Thompson"],["Email Address","alex.t@rentiq.com"],["Phone Number","+1 (555) 932-2342"],["Account Role","Vendor · User"],["Member Since","October 2023"],["Location","California, USA"]].map(([label,value]) => <div key={label}><dt className="text-[9px] font-bold uppercase tracking-wider text-[#87909a]">{label}</dt><dd className="mt-2 text-sm font-medium">{value}</dd></div>)}</dl></Card>
          <Card className="p-6"><div className="flex justify-between"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#87909a]">Vendor Wallet</p><CreditCard className="size-4 text-green-600" /></div><p className="mt-5 text-xs text-[#87909a]">Available Balance</p><p className="mt-1 text-3xl font-bold">$14,240.50</p><div className="mt-6 flex justify-between"><div><p className="text-[9px] uppercase text-[#87909a]">Frozen</p><p className="mt-1 text-sm font-bold">$1,200.00</p></div><div className="text-right"><p className="text-[9px] uppercase text-[#87909a]">Currency</p><p className="mt-1 text-sm font-bold">USD</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><button className="h-10 rounded-xl border text-xs font-bold">Adjust Balance</button><button className="h-10 rounded-xl bg-[#f73030] text-xs font-bold text-white">History</button></div></Card>
        </div>

        <div className="grid gap-6 xl:grid-cols-[1.3fr_1fr]">
          <Card className="p-6"><div className="flex justify-between"><h2 className="font-bold">Identity Verification</h2><span className="rounded-full border border-amber-300 bg-amber-50 px-2 py-1 text-[9px] font-bold uppercase text-amber-600">Pending</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><p className="mb-2 text-[9px] font-bold uppercase text-[#87909a]">ID Front View</p><Image src="/img/admin/id-front.png" alt="Identity card front" width={480} height={260} className="h-44 w-full rounded-lg border-4 border-[#3f4649] object-cover" /></div><div><p className="mb-2 text-[9px] font-bold uppercase text-[#87909a]">ID Back View</p><Image src="/img/admin/id-back.png" alt="Identity card back" width={480} height={260} className="h-44 w-full rounded-lg border-4 border-[#3f4649] object-cover" /></div></div><label className="mt-6 block text-[9px] font-bold uppercase text-[#87909a]">Administrative Feedback<textarea placeholder="State reason if rejection is necessary..." className="mt-2 h-28 w-full resize-none rounded-xl border bg-[#f7f9fc] p-4 text-xs font-normal normal-case outline-none" /></label><div className="mt-4 flex gap-3"><button className="flex h-11 items-center gap-2 rounded-xl bg-[#f73030] px-6 text-xs font-bold text-white"><Check className="size-4" /> Approve</button><button className="h-11 rounded-xl border px-8 text-xs font-bold">Reject</button></div></Card>
          <Card className="p-6"><div className="flex justify-between"><h2 className="font-bold">Performance Intelligence</h2><span className="rounded bg-[#f1f4f8] px-2 py-1 text-[9px] text-[#87909a]">Last 30 Days</span></div><div className="mt-5 grid grid-cols-2 gap-4">{[["Acceptance","98.4%",TrendingUp,"text-green-600"],["Cancellation","1.2%",AlertTriangle,"text-red-500"],["Rating","4.9 ★",Star,"text-amber-500"],["Response","12m",Clock3,"text-blue-500"]].map(([label,value,Icon,color]) => { const MetricIcon = Icon as typeof TrendingUp; return <div key={label as string} className="rounded-xl border p-4"><p className="text-[9px] font-bold uppercase text-[#87909a]">{label as string}</p><div className="mt-2 flex items-center gap-2"><p className="text-xl font-bold">{value as string}</p><MetricIcon className={`size-4 ${color as string}`} /></div></div>; })}</div><div className="mt-6 flex justify-between"><p className="text-[10px] font-bold uppercase text-[#87909a]">Compliance Audit</p><button className="text-[10px] font-bold text-red-600">Full History</button></div><div className="mt-4 space-y-5">{[["Facial Recognition Passed","Automated identity match successful against government records.","2d ago",ShieldCheck,"bg-green-50 text-green-600"],["Cross-Account Entity Found","Identification metadata linked to legacy account #USR-4100.","4d ago",AlertTriangle,"bg-amber-50 text-amber-600"]].map(([title,detail,ago,Icon,color]) => { const AuditIcon = Icon as typeof ShieldCheck; return <div key={title as string} className="flex gap-3"><span className={`grid size-8 shrink-0 place-items-center rounded-full ${color as string}`}><AuditIcon className="size-4" /></span><div><p className="text-xs font-bold">{title as string}</p><p className="mt-1 text-[10px] leading-4 text-[#87909a]">{detail as string}</p></div><span className="ml-auto text-[9px] text-[#87909a]">{ago as string}</span></div>; })}</div></Card>
        </div>

        <Card className="overflow-hidden"><div className="flex justify-between px-6 py-5"><h2 className="font-bold">Recent Booking Transactions</h2><button className="flex items-center gap-1 text-[10px] font-bold text-red-600">View All Transactions <ArrowRight className="size-3" /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-[#fafbfc] text-[9px] font-bold uppercase text-[#87909a]"><tr><th className="px-8 py-4">Booking ID</th><th>Asset / Property</th><th>Dates</th><th>Status</th><th>Amount</th></tr></thead><tbody className="divide-y">{bookings.map(([id,name,location,dates,nights,status,amount,image]) => <tr key={id} className="h-[72px] text-xs"><td className="px-8">{id}</td><td><div className="flex items-center gap-3"><Image src={image} alt="" width={40} height={40} className="size-10 rounded-lg object-cover" /><div><p className="font-bold">{name}</p><p className="text-[9px] text-[#87909a]">{location}</p></div></div></td><td><p>{dates}</p><p className="text-[9px] text-[#87909a]">{nights}</p></td><td><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${status === "Completed" ? "bg-green-50 text-green-600" : status === "Active" ? "bg-blue-50 text-blue-600" : "bg-orange-50 text-orange-600"}`}>{status}</span></td><td className="font-bold">{amount}</td></tr>)}</tbody></table></div><footer className="flex items-center justify-between border-t px-6 py-4 text-[9px] text-[#87909a]"><p>Showing 1 to 3 of 3 transactions</p><div className="flex gap-2"><button className="grid size-8 place-items-center rounded-md border"><ChevronLeft className="size-3" /></button>{[1,2,3].map(page => <button key={page} className={`size-8 rounded-md border ${page === 1 ? "border-red-500 bg-red-500 text-white" : ""}`}>{page}</button>)}<button className="grid size-8 place-items-center rounded-md border"><ChevronRight className="size-3" /></button></div></footer></Card>

        <div className="grid gap-6 xl:grid-cols-[1fr_2.15fr]"><section className="rounded-2xl bg-[#dde6f2] p-6"><h2 className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="size-4 text-red-600" /> Compliance Policy</h2><div className="mt-5 rounded-lg bg-white/70 p-4"><p className="text-[9px] uppercase text-[#87909a]">Current Violation Tier</p><p className="mt-1 text-sm">Tier 0 (No Violations)</p></div><h3 className="mt-6 text-xs font-bold">Suspension Rules:</h3><ul className="mt-3 space-y-2 text-[10px] leading-4 text-[#5c5f61]"><li><span className="text-red-500">•</span> First Strike: 24h cooling period for minor infractions.</li><li><span className="text-red-500">•</span> Identity Fraud: Instant permanent ban and wallet freeze.</li><li><span className="text-red-500">•</span> Escrow Bypass: 7-day suspension & 10% penalty fee.</li></ul></section><Card className="p-6"><h2 className="font-bold">Internal Action Log</h2><div className="relative mt-6 space-y-7 before:absolute before:bottom-5 before:left-[11px] before:top-5 before:w-px before:bg-[#e1e5ea]">{activity.map(({ title,detail,date,time,actor,icon:Icon,color,current }) => <div key={title} className="relative flex gap-4 pl-10"><span className={`absolute left-0 top-1 grid size-6 place-items-center rounded-full border-2 bg-white ${current ? "border-red-500" : "border-[#e1e5ea]"}`}><span className={`size-2 rounded-full ${current ? "bg-red-500" : "bg-[#e1e5ea]"}`} /></span><div className={`grid size-9 shrink-0 place-items-center rounded-lg ${color}`}><Icon className="size-4" /></div><div className="flex-1"><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[10px] text-[#87909a]">{detail}</p></div><div className="hidden text-right sm:block"><p className="text-[10px] font-bold">{date} <span className="font-normal text-[#87909a]">· {time}</span></p><p className="mt-1 text-[9px] text-[#87909a]">{actor}</p></div></div>)}</div><button className="mt-7 flex items-center gap-1 text-[10px] font-bold text-red-600">View Full Activity Log <ArrowRight className="size-3" /></button></Card></div>
      </div>
    </main>
  );
}
