"use client";

import Link from "next/link";
import { Heart, MapPin } from "lucide-react";
import { useGetFavoritesQuery, useRemoveFavoriteMutation } from "@/redux/services/renterApi";

type Favorite = { id?: string; itemId?: string; thumbnailUrl?: string; item?: { id?: string; title?: string; primaryImageUrl?: string; pricePerDay?: number; locationText?: string }; title?: string; imageUrl?: string; pricePerDay?: number; locationText?: string };

export default function FavoritesPage() {
  const { data, isLoading, isError } = useGetFavoritesQuery({ "pageable.page": 0, "pageable.size": 50, "pageable.sort": "favoritedAt,desc" });
  const [removeFavorite] = useRemoveFavoriteMutation();
  const favorites = Array.isArray(data) ? data as Favorite[] : Array.isArray((data as { content?: unknown[] } | undefined)?.content) ? (data as { content: Favorite[] }).content : [];
  return <main className="min-h-screen bg-[#f7f8fb] px-6 py-10 sm:px-12 lg:px-24"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#F73030]">Your collection</p><h1 className="mt-2 text-3xl font-bold text-[#253C95]">Saved Wishlist</h1><p className="mt-2 text-sm text-slate-500">Items you saved for your next rental.</p></div><Heart className="size-8 fill-[#F73030] text-[#F73030]" /></div>{isLoading ? <p className="mt-12 text-center text-sm text-slate-500">Loading saved items...</p> : isError ? <p className="mt-12 text-center text-sm text-red-600">Unable to load saved items.</p> : favorites.length === 0 ? <div className="mt-12 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><Heart className="mx-auto size-10 text-slate-300" /><p className="mt-4 font-semibold text-slate-700">No saved items yet</p><Link href="/items" className="mt-5 inline-flex rounded-xl bg-[#F73030] px-5 py-3 text-sm font-bold text-white">Browse items</Link></div> : <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{favorites.map((favorite) => { const item = favorite.item; const itemId = item?.id || favorite.itemId || favorite.id || ""; return <article key={itemId} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex h-48 items-center justify-center bg-slate-50"><img src={item?.primaryImageUrl || favorite.thumbnailUrl || favorite.imageUrl || "/img/electronics.png"} alt={item?.title || favorite.title || "Saved item"} className="size-full object-contain p-5" /></div><div className="p-5"><h2 className="font-bold text-slate-900">{item?.title || favorite.title || "Saved item"}</h2><p className="mt-2 text-sm text-[#F73030]">${item?.pricePerDay ?? favorite.pricePerDay ?? 0} / day</p><p className="mt-2 flex items-center gap-1 text-xs text-slate-500"><MapPin className="size-3.5" />{item?.locationText || favorite.locationText || "Location unavailable"}</p><div className="mt-5 flex gap-2"><Link href={`/items/${itemId}`} className="flex-1 rounded-lg bg-[#253C95] px-3 py-2 text-center text-xs font-bold text-white">View item</Link><button type="button" onClick={() => removeFavorite(itemId)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 hover:border-red-200 hover:text-[#F73030]">Remove</button></div></div></article>; })}</div>}</div></main>;
}